drivers: misc/mediatek: Remove redefinition of 'vm_fault_t'
* ./include/linux/mm_types.h:25:13: note: previous definition is here
25 | typedef int vm_fault_t;

Signed-off-by: Ansh <singhansh64321@gmail.com>
Signed-off-by: Naveen <133593113+elohim-etz@users.noreply.github.com>
(cherry picked from commit 04f2fbdfcba4fde37c9a8743828de2fc25ba1c6b)